zaya_shope/cart_app/urls.py
from django.contrib import admin
from django.urls import path

from cart_app import views

urlpatterns = [

    path('cart/',views.cart,name='cart'),
    path("checkout/", views.checkout, name="checkout"),  
    path("add_address/",views.add_address,name="add_address"),
    path('place_order/',views.place_order,name="place_order"),
    path('addto_cart/<int:id>/',views.addto_cart,name="addto_cart"),
    path('edit_address/<int:id>/',views.edit_address,name="edit_address"),
    path('delete_address/<int:id>',views.delete_address,name="delete_address"),
    path('remove_cart/<int:id>/',views.remove_cart,name="remove_cart"),
    path('update_qnty/<int:id>/',views.update_qnty,name="update_qnty"),
    path('success/',views.success,name="success"),
    path('my_order/',views.my_order,name="my_order"),
    path('cancel_oder/<int:id>/',views.cancel_order,name="cancel_order"),
    path('order_summary/<int:id>/',views.order_summary,name="order_summary"),
    path("invoice/<int:id>/download/", views.invoice_pdf, name="invoice_pdf"),

    
    
   
]

zaya_shope/wishlist/urls.py
from django.contrib import admin
from django.urls import path

from wishlist import views

urlpatterns = [

    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:id>/',views.remove_from_wishlist,name='remove_from_wishlist'), 

 
]

zaya_shope/zaya_shope/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

handler404 = 'zaya_app.views.custom_404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('zaya_app.urls')),
    path('admin_app',include('admin_app.urls')),
    path('cart',include('cart_app.urls')),
    path('discount',include('discount_app.urls')),
    path('wishlist',include('wishlist.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

zaya_shope/cart_app/models.py
from django.db import models
from zaya_app.models import User
from admin_app.models import Products
from discount_app.models import Discount


# Create your models here.

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    exact_total = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    saving = models.DecimalField(max_digits=8,decimal_places=2,default=0)
    number_of_items = models.IntegerField(default=1)


class CartItem(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE) 
    qnty = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=8,decimal_places=2,default=0)

class ShippingAddress(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    main_address = models.TextField()
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pincode = models.CharField(max_length=10)
    phone = models.CharField( max_length=50, unique=True, null=False, blank=False)

class Order(models.Model):
    
    STATUS = [
        ("ordered", "ordered"),
        ("Processing", "Processing"),
        ("Shipped", "Shipped"),
        ("Delivered", "Delivered"),
        ("Cancelled", "Cancelled"),
    ]
    PAYMENT_METHODS = [
        ("UPI","UPI"),
        ("COD","cash on delivery"),
    ]
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    address = models.ForeignKey(ShippingAddress, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    payment_status = models.CharField(max_length=20, default="Pending")  
    status = models.CharField(max_length=20, choices=STATUS, default="ordered")
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS, default="COD")
    
    
    
class OrderItems(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    qnty=models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2) 
    

    
            

zaya_shope/wishlist/models.py
from django.db import models
from zaya_app.models import User

from admin_app.models import Products 

# Create your models here.
class Wishlist(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    added_a = models.DateTimeField(auto_now_add=True)

zaya_shope/wishlist/views.py
from django.shortcuts import render,redirect
from .models import Wishlist
from admin_app.models import Products
from zaya_app.models import User
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from wishlist import urls
from django.contrib import messages
@login_required
def wishlist(request):
    wishlist_items = Wishlist.objects.filter(user=request.user)
    return render(request,'user/wishlist.html',locals())

@login_required
def add_to_wishlist(request,id):
    product = Products.objects.get(id=id)
    wishlist_items = Wishlist.objects.filter(user=request.user)
    if product in wishlist_items:
        messages.info(request, "Product already in wishlist")
    else:
        wishlist = Wishlist.objects.create(user=request.user,product=product)
    return redirect(request.META.get("HTTP_REFERER", "/"))

@login_required(login_url='login')
def remove_from_wishlist(request,id):
    wishlist_item = Wishlist.objects.get(user=request.user, product_id=id)
    wishlist_item.delete()
    return redirect(request.META.get("HTTP_REFERER", "/"))

zaya_shope/templates/user/account.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="container d-flex py-4 bg-light " >
    <div class="  card   border-0 shadow-sm rounded-4 mb-4 overflow-hidden order-card col-md-6 p-5">
        <div class="col-md-12 justify-content-center align-items-center">
            <div class="card border-0 shadow-sm justify-content-center align-items-center">
                <div class="rounded-circle bg-success text-white d-flex justify-content-center align-items-center mt-3"
                    style="width:98px; height:91px; font-size:50px !important; font-weight:bold !important">
                    {{ user.username|first|upper }}
                </div>
                
                <p class="mt-3 fw-semibold">{{user.username}}</p>
            </div>
             
        </div>
        <div class="d-flex col-md-12  ms-5 ">
            <div class="col-md-2 mt-2 ms-5 justify-content-center align-items-center">
              <img src="{% static 'img/img/order.png' %}" style="width:35px !important; height:42px !important;">
            </div>
             <div class="col-md-10">
                <a class="text-decoration-none text-dark" href="{% url 'my_order' %}"><p class="mt-3 fw-semibold">My Orders</p></a>
            
            </div>
        </div>
        <div class="d-flex col-md-12 ms-5">
            <div class="col-md-2 mt-2 ms-5 justify-content-center align-items-center">
              <img src="{% static 'img/img/cart.png' %}" style="width:35px !important; height:42px !important;">
            </div>
             <div class="col-md-10">
                <a class="text-decoration-none text-dark" href="{% url 'cart' %}"><p class="mt-3 fw-semibold">Cart</p></a>
            </div>
        </div>
        <div class="d-flex col-md-12 ms-5">
            <div class="col-md-2 mt-2 ms-5 justify-content-center align-items-center">
              <img src="{% static 'img/img/hearts.png' %}" style="width:35px !important; height:42px !important;">
            </div>
             <div class="col-md-10">
                <a class="text-decoration-none text-dark" href="{% url 'wishlist' %}"><p class="mt-3 fw-semibold">wishlist</p></a>
            </div>
        </div>
        <div class="d-flex col-md-12 ms-5">
            <div class="col-md-2 mt-2 ms-5 justify-content-center align-items-center">
              <img src="{% static 'img/img/logout.png' %}" style="width:35px !important; height:42px !important;">
            </div>
             <div class="col-md-10">
                <a class="text-decoration-none text-dark" href="{% url 'logout' %}"><p class="mt-3 fw-semibold">Logout</p></a>
            </div>
        </div>
    </div>
    <div class="  card   border-0 shadow-sm rounded-4 mb-4 overflow-hidden order-card col-md-6">
        <div class="d-flex col-md-12">
            <div class="col-md-6 mt-2 ms-5">
                <h4>Personal Information</h4> 
            </div>
            <div class="col-md-6 mt-2 ">
              <a href="" class="text-decoration-none">
                <button type="submit" class="btn btn-success">Edit</button>
              </a><a href="" class="text-decoration-none">
                <button type="submit" class="btn btn-success" >Logout</button>
              </a>

            </div>
        </div>
        <div class="col-md-12 mt-2 ms-5 justify-content-center align-items-center ">
            
           
           <div class="row  mt-3 col-md-10  border-0 shadow-sm pb-2">
                <div class=" fw-semibold  ms-3">Full Name: {{ user.username }} </div>
                <div class=" fw-semibold  ms-3">Email: {{ user.email}} </div>
                <div class=" fw-semibold  ms-3">Phone: {{ user.phone }} </div>
                <div class=" fw-semibold  ms-3">Joined: {{ user.date_joined|date:"M d, Y" }} </div>

            </div>
        </div>
        <div class="col-md-12 mt-3 ms-5 justify-content-center align-items-center ">
            <div class="row  mt-3 col-md-10  border-0 shadow-sm pb-2">
                <div class="info-card">
                    <span class="info-label">Default Address:</span>
                    {% if address %}
                        <div class=" fw-semibold  ms-3">Place: {{ user.main_address }} </div>
                        <div class=" fw-semibold  ms-3">City: {{ user.city }} </div>
                        <div class=" fw-semibold  ms-3">State: {{ user.state }} </div>
                        <div class=" fw-semibold  ms-3">Pincode: {{ user.pincode }} </div>
                    {% else %}
                      <p>No address added yet</p>
                    {% endif %}
                </div>
            </div>
        </div>


            
            
       
        
    </div>
 
</div>
{% endblock %}

zaya_shope/templates/user/cart.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <!-- Cart Items -->
    <div class="col-lg-8">
      <h3 class="fw-bold mb-4">🛒 Your Cart</h3>
    {% if cart_items %}
      {% for item in cart_items %}
        <div class="card mb-4 shadow-sm border-0 rounded-4">
          <div class="row g-0 align-items-center">
            <!-- Product Image -->
            <div class="col-md-3">
              <img src="{{ item.product.image.url }}" class="img-fluid rounded me-6" style="width:70px; height:70px; object-fit:cover;" alt="{{ item.product.name }}">
              <form method="POST" action="{% url 'update_qnty' item.id %}" class="d-flex align-items-center gap-2">
                  {% csrf_token %}
                  <button type="submit" name="action" value="decrement" class="btn btn-outline-success btn-sm rounded-circle">−</button>
                  <input type="text" value="{{ item.qnty }}" readonly class="form-control text-center border-0 bg-light" style="width: 40px; height:30px; font-size:20px !important;">
                  <button type="submit" name="action" value="increment" class="btn btn-outline-success btn-sm rounded-circle">+</button>
              </form>
            </div>

            <!-- Product Info -->
            <div class="col-md-6">
              <div class="card-body">
                <h5 class="card-title fw-semibold">{{ item.product.name }}</h5>
                  {% if item.product.discount %}
                    <span class="text-muted text-decoration-line-through">₹{{ item.product.price }}</span>
                    <span class="text-dark fw-bold ms-2">₹{{ item.product.discount.discount_price }} ({{ item.product.discount.percentage }} % off)</span>
                    {% comment %} <h6 class="fw-bold mb-0">₹{{ saving }}</h6> {% endcomment %}
                  {% else %}
                    <span class="product-price">₹{{ item.product.price }}</span>
                  
                

                <!-- Subtotal -->
                <div class="mt-3">
                  <small class="text-muted">Subtotal</small>
                  
                  <h6 class="fw-bold mb-0">₹{{ item.subtotal }}</h6>
                </div>
                {% endif %}
              </div>
            </div>

            <!-- Remove -->
            <div class="col-md-3 text-end pe-4">
              <a href="{% url 'remove_cart' item.id %}" class="btn btn-outline-danger btn-sm rounded-pill">Remove 🗑️</a>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="col-12">
        <div class="d-flex justify-content-center align-items-center flex-column text-center" style="height: 70vh;">
          <h4 class="text-muted mb-3"> Your cart is empty.</h4>
          <a href="{% url 'shop' %}" class="btn btn-success rounded-pill px-4">
            Continue Shopping
          </a>
        </div>
      </div>
    {% endif %}
        

      
   </div>

    <!-- Order Summary -->
     {% if cart_items %}
      <div class="col-lg-4">
        <div class="card shadow-lg border-0 rounded-4 p-4">
          <h5 class="fw-bold mb-3">Order Summary</h5>
          <div class="d-flex justify-content-between text-success fw-bold">
            <span>ExactTotal </span>
            <span>₹{{ cart.exact_total }}</span>
          </div>
          <div class="d-flex justify-content-between text-success fw-bold">
            <span>your saving</span>
            <span>₹{{ cart.saving }}</span>
          </div>
          <hr>
          <div class="d-flex justify-content-between">
            <span>Total</span>
            <span>₹{{ cart.total }}</span>
          </div>
          <div class=" justify-content-between">
            <a href="{% url 'checkout' %}"><button  class="btn btn-success w-100">Checkout</button>
          </div>
        </div>
      </div>
     {% endif %}
  </div>
</div>
{% endblock %}

zaya_shope/templates/user/checkout.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="container py-5">
  <div class="row g-4">
    <form method="POST" action="{% url 'checkout' %}" class="d-flex">
      {% csrf_token %}

          <div class="card shadow-sm col-lg-8">
              <h4> Delivery Address</h4>
              {% for address in addresses %}
               
                <div class="border rounded-3 p-3 mb-3 bg-light">
                  <input class="form-check-input" type="radio" name="address" id="online" value="{{address.id}}" required>
                  <p class="mb-1"><strong>Address:</strong> {{ address.main_address }}</p>
                  <p class="mb-1"><strong>Phone:</strong> {{ address.phone }}</p>
                  <p class="mb-1"><strong>City:</strong> {{ address.city }}</p>
                  <p class="mb-1"><strong>State:</strong> {{ address.state }}</p>
                  <p class="mb-0"><strong>Pincode:</strong> {{ address.pincode }}</p>
                  <a href="{% url 'edit_address' address.id %}" class="btn btn-outline-primary btn-sm rounded-pill px-3">
                    Edit
                  </a>
                </div>
              {% endfor %}
              <div class="card shadow-sm w-50">
                <button type="button" class="btn btn-success" 
                        data-bs-toggle="modal" data-bs-target="#add_address">
                    Add Address
                </button>
              </div>
          </div>
        


        

          <!-- Payment & Place Order -->
          <div class="col-lg-4 ms-4"  >
            <div class="card shadow-lg border-0 rounded-4 p-4">
              <h5 class="fw-bold mb-3">Payment Method</h5>
              <div class="mb-3">
                <select class="form-select shadow-sm border-1 rounded-3" name="payment_method" required>
                  <option value="" >Select a payment method</option>
                  {% for method in payment_methods %}
                    <option value="{{ method }}">{{ method }}</option>
                  {% endfor %}
                </select>
              </div>
              
              <h5 class="fw-bold mb-3">Order Summary</h5>
              <div class="d-flex justify-content-between text-success fw-bold">
                <span>ExactTotal </span>
                <span>₹{{ cart.exact_total }}</span>
              </div>
              <div class="d-flex justify-content-between text-success fw-bold">
                <span>your saving</span>
                <span>₹{{ cart.saving }}</span>
              </div>
              <hr>
              <div class="d-flex justify-content-between">
                <span>Total</span>
                <span>₹{{ cart.total }}</span>
              </div>
              <div class=" justify-content-between">
               <button type="submit" class="btn btn-success w-100 py-2 fw-bold">place order<button>
              </div>
          </div>
        </div>
    </form>


          {% comment %} add_address modal {% endcomment %}

      <div class="modal fade" id="add_address" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content" style="border-radius: 20px; background: rgba(255, 255, 255, 0.9); backdrop-filter: blur(10px); border: none; box-shadow: 0 10px 25px rgba(0,0,0,0.1);">

            <div class="modal-header border-0">
              <h5 class="modal-title">Add New Address</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>

            <form action="{% url 'add_address' %}" method="POST">
              {% csrf_token %}
              <div class="modal-body">

                <div class="mb-3">
                  <label class="form-label">Main Address</label>
                  <input class="form-control" name="main_address" required>
                </div>

                <div class="mb-3">
                  <label class="form-label">Phone Number</label>
                  <input class="form-control" name="phone" required>
                </div>

                <div class="mb-3">
                  <label class="form-label">City</label>
                  <input class="form-control" name="city" required>
                </div>

                <div class="mb-3">
                  <label class="form-label">State</label>
                  <input class="form-control" name="state" required>
                </div>

                <div class="mb-3">
                  <label class="form-label">Pincode</label>
                  <input class="form-control" name="pincode" required>
                </div>

              </div>

              <div class="modal-footer border-0">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success">Add Address</button>
              </div>

            </form>

          </div>
        </div>
      </div>


  </div>
</div>





{% endblock %}

zaya_shope/templates/user/contact.html
{% extends "user/base.html" %}
{% load static %}
{% block title %}About {% endblock %}
{% block content %}


    <!-- Load map styles -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
<!--
    
TemplateMo 559 Zay Shop

https://templatemo.com/tm-559-zay-shop

-->


    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>


    <!-- Start Content Page -->
    <div class="container-fluid bg-light py-5">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1">Contact Us</h1>
            <p>
                Proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet.
            </p>
        </div>
    </div>

    <!-- Start Map -->
    <div id="mapid" style="width: 100%; height: 300px;"></div>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>
    <script>
        var mymap = L.map ('mapid').setView([-23.013104, -43.394365, 13], 13);

        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 18,
            attribution: 'Zay Telmplte | Template Design by <a href="https://templatemo.com/">Templatemo</a> | Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1
        }).addTo(mymap);

        L.marker([-23.013104, -43.394365, 13]).addTo(mymap)
            .bindPopup("<b>Zay</b> eCommerce Template<br />Location.").openPopup();

        mymap.scrollWheelZoom.disable();
        mymap.touchZoom.disable();
    </script>
    <!-- Ena Map -->

    <!-- Start Contact -->
    <div class="container py-5">
        <div class="row py-5">
            <form class="col-md-9 m-auto" method="post" role="form">
                <div class="row">
                    <div class="form-group col-md-6 mb-3">
                        <label for="inputname">Name</label>
                        <input type="text" class="form-control mt-1" id="name" name="name" placeholder="Name">
                    </div>
                    <div class="form-group col-md-6 mb-3">
                        <label for="inputemail">Email</label>
                        <input type="email" class="form-control mt-1" id="email" name="email" placeholder="Email">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="inputsubject">Subject</label>
                    <input type="text" class="form-control mt-1" id="subject" name="subject" placeholder="Subject">
                </div>
                <div class="mb-3">
                    <label for="inputmessage">Message</label>
                    <textarea class="form-control mt-1" id="message" name="message" placeholder="Message" rows="8"></textarea>
                </div>
                <div class="row">
                    <div class="col text-end mt-2">
                        <button type="submit" class="btn btn-success btn-lg px-3">Let’s Talk</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- End Contact -->


   

    <!-- Start Script -->
    <script src="assets/js/jquery-1.11.0.min.js"></script>
    <script src="assets/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/templatemo.js"></script>
    <script src="assets/js/custom.js"></script>
    <!-- End Script -->
{% endblock %}

zaya_shope/templates/user/edit_address.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5 d-flex justify-content-center">
  <div class="card shadow-lg border-0 p-4" style="max-width: 600px; width: 100%; border-radius: 15px;">
    <h3 class="fw-bold text-center mb-4">Edit Product</h3>
    
    <form action="{% url 'edit_address' address.id %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      
      <div class="mb-3">
        <label for="name" class="form-label fw-semibold">Main Address:</label>
        <input type="text" class="form-control" id="name" name="main_address" value="{{address.main_address }}" required>
      </div>

      
      <div class="mb-3">
        <label for="price" class="form-label fw-semibold">City</label>
        <input type="text" class="form-control" id="price" name="city" value="{{address.city }}" required>
      </div>
      <div class="mb-3">
        <label for="price" class="form-label fw-semibold">State</label>
        <input type="text" class="form-control" id="price" name="state" value="{{address.state }}" required>
      </div>
      <div class="mb-3">
        <label for="price" class="form-label fw-semibold">Pincode</label>
        <input type="text" class="form-control" id="price" name="pincode" value="{{address.pincode }}" required>
      </div>
      <div class="mb-3">
        <label for="price" class="form-label fw-semibold">Phone</label>
        <input type="text" class="form-control" id="price" name="phone" value="{{address.phone }}" required>
      </div>
      <div class="d-flex justify-content-between mt-4">
        <a href="{% url 'checkout' %}" class="btn btn-outline-secondary rounded-pill px-4">Cancel</a>
        <button type="submit" class="btn btn-success rounded-pill px-4">Update Address</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

zaya_shope/templates/user/my_order.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="container py-4">
    <h3 class="mb-4 text-center fw-bold">My Orders</h3>

    {% for item in order %}
    <div class="order-card shadow-sm rounded-4 mb-4 p-0">

        <!-- Header -->
        <div class="order-header d-flex justify-content-between align-items-center px-4 py-3">
            <h5 class="fw-semibold m-0">Order ID: #000000{{ item.id }}</h5>
            <span class="fw-semibold">{{ item.created_at|date:"M d, Y" }}</span>
        </div>

        <!-- Body -->
        <div class="row g-0 p-4 align-items-center">
          
            <!-- LEFT DETAILS -->
            <div class="col-md-4">
                <p class="m-0"><strong>Date:</strong> {{ item.created_at|date:"M d, Y" }}</p>
                <p class="mt-2 m-0">
                    <strong>Total:</strong> ₹{{ item.total }}
                </p>
                <p class="mt-2 m-0">
                    <strong>Status:</strong> {{ item.status }}
                </p>
                
            </div>
            


            <!-- CENTER -->
            <div class="col-md-4 text-center">
                <p class="mt-1 w-50 m-0 d-inline ">
                    <strong>Est. Delivery:</strong> {{ expected_delivery }}
                </p>
                <a href="{% url 'order_summary' item.id %}"
                   class="btn btn-outline-success px-4 py-2 rounded-pill mt-2">
                    View Summary
                </a>
                {% if item.status != "Cancelled" and item.status != "Delivered" %}
                    <a href="{% url 'cancel_order' item.id %}" 
                    class="btn btn-outline-danger px-4 py-2 rounded-pill mt-1">
                        Cancel Order
                    </a>
                {% endif %}
            </div>

            <!-- RIGHT IMAGES -->
            <div class="col-md-4 d-flex justify-content-end">
                {% for order_item in item.orderitems_set.all %}
                    {% if forloop.counter <= 2 %}
                        <img src="{{ order_item.product.image.url }}" 
                             class="order-img rounded-3 ms-2">
                    {% endif %}
                {% endfor %}
            </div>
         
        </div>
    </div>
    {% empty %}
    <p class="text-center">No orders found.</p>
    {% endfor %}
</div>

{% endblock %}

zaya_shope/templates/user/order_success.html
{% extends 'user/base.html' %}
{% load static %}

{% block content %}
<div class="container py-5 d-flex justify-content-center align-items-center min-vh-75">
  <div class="card shadow-lg border-0 rounded-4 p-5 text-center" style="max-width: 600px;">
    
    <h2 class="fw-bold text-success mb-3">Your Order Has Been Placed Successfully!</h2>
    <p class="text-muted mb-4">Thank you for shopping with <span class="fw-semibold text-dark">Zaya Accessories</span> 💖<br>
    You will receive a confirmation email with your order details shortly.</p>
    
    <div class="d-flex justify-content-center gap-3">
      <a href="{% url 'shop' %}" class="btn btn-success px-4 py-2 rounded-pill fw-semibold">
        Continue Shopping
      </a>
      <a href="{% url 'my_order' %}" class="btn btn-success px-4 py-2 rounded-pill fw-semibold">
        My Orders
      </a>
    </div>
  </div>
</div>
{% endblock %}